// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbital.API.Data;

#nullable disable

namespace Orbital.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260511004602_v7_SchemaFix")]
    partial class v7_SchemaFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Orbital.API.Models.CoordenadasPlaneta", b =>
                {
                    b.Property<int>("Id_Coordenada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_coordenada");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Coordenada"));

                    b.Property<decimal>("Coordenada_X")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coordenada_x");

                    b.Property<decimal>("Coordenada_Y")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coordenada_y");

                    b.Property<decimal>("Coordenada_Z")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coordenada_z");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.HasKey("Id_Coordenada");

                    b.HasIndex("Id_Planeta")
                        .IsUnique();

                    b.ToTable("coordenada_planeta", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Galaxia", b =>
                {
                    b.Property<int>("Id_Galaxia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_galaxia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Galaxia"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id_Galaxia");

                    b.ToTable("galaxia", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Jerarquia", b =>
                {
                    b.Property<int>("Id_Jerarquia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Jerarquia"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Jerarquia");

                    b.ToTable("jerarquia", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Mision", b =>
                {
                    b.Property<int>("Id_Mision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mision");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Mision"));

                    b.Property<DateTime>("Fecha_Asignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("Fecha_Fin_Estimada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin_estimada");

                    b.Property<DateTime?>("Fecha_Fin_Real")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin_real");

                    b.Property<DateTime?>("Fecha_Inicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("Id_Comandante")
                        .HasColumnType("int")
                        .HasColumnName("id_comandante");

                    b.Property<int>("Id_Equipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<int>("Id_Estado_Mision")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_mision");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<string>("Nombre_Mision")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_mision");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Porcentaje_Avance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("porcentaje_avance");

                    b.Property<byte>("Prioridad")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("prioridad");

                    b.Property<decimal>("Recompensa_Ofrecida")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("recompensa_ofrecida");

                    b.Property<string>("Tipo_Mision")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_mision");

                    b.HasKey("Id_Mision");

                    b.HasIndex("Id_Planeta");

                    b.ToTable("mision", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Planeta", b =>
                {
                    b.Property<int>("Id_Planeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Planeta"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Color1")
                        .HasColumnType("longtext")
                        .HasColumnName("color1");

                    b.Property<string>("Color2")
                        .HasColumnType("longtext")
                        .HasColumnName("color2");

                    b.Property<string>("Color3")
                        .HasColumnType("longtext")
                        .HasColumnName("color3");

                    b.Property<string>("Conquistado_Por")
                        .HasColumnType("longtext")
                        .HasColumnName("conquistado_por");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha_Descubrimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_descubrimiento");

                    b.Property<int?>("Id_Atmosfera")
                        .HasColumnType("int")
                        .HasColumnName("id_atmosfera");

                    b.Property<int>("Id_Estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int?>("Id_Galaxia")
                        .HasColumnType("int")
                        .HasColumnName("id_galaxia");

                    b.Property<int?>("Id_Propietario")
                        .HasColumnType("int")
                        .HasColumnName("id_propietario");

                    b.Property<int>("Nivel_Tecnologico")
                        .HasColumnType("int")
                        .HasColumnName("id_nivel_tecnologico");

                    b.Property<string>("Nivel_Vida_Planeta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nivel_vida_planeta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<long?>("Poblacion")
                        .HasColumnType("bigint")
                        .HasColumnName("poblacion");

                    b.HasKey("Id_Planeta");

                    b.HasIndex("Id_Atmosfera");

                    b.HasIndex("Id_Estado");

                    b.HasIndex("Id_Galaxia");

                    b.ToTable("planeta", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.PlanetaEstado", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_estado");

                    b.HasKey("Id_Estado");

                    b.ToTable("estado_planeta", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.PlanetaValoracion", b =>
                {
                    b.Property<int>("Id_Valoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_valoracion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Valoracion"));

                    b.Property<int?>("Aprobado_Por")
                        .HasColumnType("int")
                        .HasColumnName("aprobado_por");

                    b.Property<string>("Clase_Planeta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("clase_planeta");

                    b.Property<string>("Estado_Valoracion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_valoracion");

                    b.Property<DateTime?>("Fecha_Aprobacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("Fecha_Valoracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_valoracion");

                    b.Property<int>("Id_Analista")
                        .HasColumnType("int")
                        .HasColumnName("id_analista");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Poder_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("poder_score");

                    b.Property<decimal>("Precio_Final")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_final");

                    b.Property<decimal>("Recursos_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("recursos_score");

                    b.Property<decimal>("Riesgo_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("riesgo_score");

                    b.Property<decimal>("Tecnologia_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tecnologia_score");

                    b.Property<decimal>("Ubicacion_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ubicacion_score");

                    b.Property<decimal>("Valor_Total")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id_Valoracion");

                    b.HasIndex("Aprobado_Por");

                    b.HasIndex("Id_Analista");

                    b.HasIndex("Id_Planeta");

                    b.ToTable("planeta_valoracion", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Recurso", b =>
                {
                    b.Property<int>("Id_Recurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Recurso"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Rareza")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rareza");

                    b.Property<string>("Tipo_Recurso")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_recurso");

                    b.Property<string>("Unidad_Medida")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id_Recurso");

                    b.ToTable("recurso", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.RecursoPlaneta", b =>
                {
                    b.Property<int>("Id_Recurso_Planeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recurso_planeta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Recurso_Planeta"));

                    b.Property<decimal>("Cantidad_Estimada")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cantidad_estimada");

                    b.Property<bool>("Extraible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("extraible");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<int>("Id_Recurso")
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    b.Property<decimal>("Valor_Unitario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id_Recurso_Planeta");

                    b.HasIndex("Id_Planeta");

                    b.HasIndex("Id_Recurso");

                    b.ToTable("recurso_planeta", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Rol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.TipoAtmosfera", b =>
                {
                    b.Property<int>("Id_Atmosfera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_atmosfera");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Atmosfera"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id_Atmosfera");

                    b.ToTable("tipo_atmosfera", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contrasena_Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Jerarquia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Ultimo_Acceso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Id_Jerarquia");

                    b.HasIndex("Id_Rol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.CoordenadasPlaneta", b =>
                {
                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithOne("Coordenadas")
                        .HasForeignKey("Orbital.API.Models.CoordenadasPlaneta", "Id_Planeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planeta");
                });

            modelBuilder.Entity("Orbital.API.Models.Mision", b =>
                {
                    b.HasOne("Orbital.API.Models.Planeta", null)
                        .WithMany("Misiones")
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbital.API.Models.Planeta", b =>
                {
                    b.HasOne("Orbital.API.Models.TipoAtmosfera", "AtmosferaNav")
                        .WithMany()
                        .HasForeignKey("Id_Atmosfera")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbital.API.Models.PlanetaEstado", "Estado")
                        .WithMany()
                        .HasForeignKey("Id_Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Galaxia", "GalaxiaNav")
                        .WithMany()
                        .HasForeignKey("Id_Galaxia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AtmosferaNav");

                    b.Navigation("Estado");

                    b.Navigation("GalaxiaNav");
                });

            modelBuilder.Entity("Orbital.API.Models.PlanetaValoracion", b =>
                {
                    b.HasOne("Orbital.API.Models.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("Aprobado_Por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbital.API.Models.Usuario", "Analista")
                        .WithMany()
                        .HasForeignKey("Id_Analista")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithMany()
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("AprobadoPor");

                    b.Navigation("Planeta");
                });

            modelBuilder.Entity("Orbital.API.Models.RecursoPlaneta", b =>
                {
                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithMany("Recursos")
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("Id_Recurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planeta");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Orbital.API.Models.Usuario", b =>
                {
                    b.HasOne("Orbital.API.Models.Jerarquia", "Jerarquia")
                        .WithMany()
                        .HasForeignKey("Id_Jerarquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jerarquia");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Orbital.API.Models.Planeta", b =>
                {
                    b.Navigation("Coordenadas");

                    b.Navigation("Misiones");

                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
