// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orbital.API.Data;

#nullable disable

namespace Orbital.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516005252_v8_MercadoInterestelar")]
    partial class v8_MercadoInterestelar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Orbital.API.Models.AmenazaDeteccion", b =>
                {
                    b.Property<int>("Id_Amenaza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_amenaza");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Amenaza"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estado_Amenaza")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_amenaza");

                    b.Property<DateTime>("Fecha_Deteccion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_deteccion");

                    b.Property<int?>("Id_Detectado_Por")
                        .HasColumnType("int")
                        .HasColumnName("id_detectado_por");

                    b.Property<int?>("Id_Mision")
                        .HasColumnType("int")
                        .HasColumnName("id_mision");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<byte>("Nivel_Peligro")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("nivel_peligro");

                    b.Property<string>("Protocolo_Activado")
                        .HasColumnType("longtext")
                        .HasColumnName("protocolo_activado");

                    b.Property<string>("Tipo_Amenaza")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_amenaza");

                    b.HasKey("Id_Amenaza");

                    b.ToTable("amenaza_deteccion");
                });

            modelBuilder.Entity("Orbital.API.Models.Auditoria", b =>
                {
                    b.Property<long>("Id_Auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_auditoria");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id_Auditoria"));

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("accion");

                    b.Property<int?>("Id_Registro_Afectado")
                        .HasColumnType("int")
                        .HasColumnName("id_registro_afectado");

                    b.Property<int?>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Ip_Origen")
                        .HasColumnType("longtext")
                        .HasColumnName("ip_origen");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("resultado");

                    b.Property<string>("Tabla_Afectada")
                        .HasColumnType("longtext")
                        .HasColumnName("tabla_afectada");

                    b.Property<DateTime>("Timestamp_Accion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp_accion");

                    b.Property<string>("User_Agent")
                        .HasColumnType("longtext")
                        .HasColumnName("user_agent");

                    b.Property<string>("Valor_Anterior")
                        .HasColumnType("longtext")
                        .HasColumnName("valor_anterior");

                    b.Property<string>("Valor_Nuevo")
                        .HasColumnType("longtext")
                        .HasColumnName("valor_nuevo");

                    b.HasKey("Id_Auditoria");

                    b.ToTable("auditoria");
                });

            modelBuilder.Entity("Orbital.API.Models.Cliente", b =>
                {
                    b.Property<int>("Id_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_cliente");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Cliente"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Contrasena_Hash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("contrasena_hash");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("correo");

                    b.Property<decimal>("Credito_Disponible")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("credito_disponible");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int?>("Id_Galaxia_Origen")
                        .HasColumnType("int")
                        .HasColumnName("id_galaxia_origen");

                    b.Property<string>("Nivel_Confianza")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nivel_confianza");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Tipo_Cliente")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_cliente");

                    b.HasKey("Id_Cliente");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Id_Galaxia_Origen");

                    b.ToTable("cliente", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.CoordenadasPlaneta", b =>
                {
                    b.Property<int>("Id_Coordenada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_coordenada");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Coordenada"));

                    b.Property<decimal>("Coordenada_X")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coordenada_x");

                    b.Property<decimal>("Coordenada_Y")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coordenada_y");

                    b.Property<decimal>("Coordenada_Z")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("coordenada_z");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.HasKey("Id_Coordenada");

                    b.HasIndex("Id_Planeta")
                        .IsUnique();

                    b.ToTable("coordenada_planeta", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Galaxia", b =>
                {
                    b.Property<int>("Id_Galaxia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_galaxia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Galaxia"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id_Galaxia");

                    b.ToTable("galaxia", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.HistoricoCicloPlanetario", b =>
                {
                    b.Property<int>("Id_Historico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_historico");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Historico"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha_Cambio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_cambio");

                    b.Property<int?>("Id_Cliente_Anterior")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente_anterior");

                    b.Property<int?>("Id_Cliente_Nuevo")
                        .HasColumnType("int")
                        .HasColumnName("id_cliente_nuevo");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<int?>("Id_Transaccion")
                        .HasColumnType("int")
                        .HasColumnName("id_transaccion");

                    b.Property<string>("Tipo_Evento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_evento");

                    b.HasKey("Id_Historico");

                    b.HasIndex("Id_Cliente_Anterior");

                    b.HasIndex("Id_Cliente_Nuevo");

                    b.HasIndex("Id_Planeta");

                    b.HasIndex("Id_Transaccion");

                    b.ToTable("historico_ciclo_planetario", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Jerarquia", b =>
                {
                    b.Property<int>("Id_Jerarquia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_jerarquia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Jerarquia"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<int>("Nivel_Poder_Maximo")
                        .HasColumnType("int")
                        .HasColumnName("nivel_poder_maximo");

                    b.Property<int>("Nivel_Poder_Minimo")
                        .HasColumnType("int")
                        .HasColumnName("nivel_poder_minimo");

                    b.Property<string>("Nombre_Jerarquia")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_jerarquia");

                    b.HasKey("Id_Jerarquia");

                    b.ToTable("jerarquia", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.MercadoPlaneta", b =>
                {
                    b.Property<int>("Id_Publicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_publicacion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Publicacion"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Descripcion_Venta")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion_venta");

                    b.Property<DateTime>("Fecha_Publicacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_publicacion");

                    b.Property<DateTime?>("Fecha_Vencimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_vencimiento");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<int>("Id_Publicado_Por")
                        .HasColumnType("int")
                        .HasColumnName("id_publicado_por");

                    b.Property<int>("Id_Valoracion")
                        .HasColumnType("int")
                        .HasColumnName("id_valoracion");

                    b.Property<decimal>("Precio_Minimo")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_minimo");

                    b.Property<decimal>("Precio_Publicado")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_publicado");

                    b.HasKey("Id_Publicacion");

                    b.HasIndex("Id_Planeta");

                    b.HasIndex("Id_Valoracion");

                    b.ToTable("mercado_planeta");
                });

            modelBuilder.Entity("Orbital.API.Models.MiembroEquipo", b =>
                {
                    b.Property<int>("Id_Miembro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_miembro");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Miembro"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<DateTime>("Fecha_Ingreso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_ingreso");

                    b.Property<int>("Id_Equipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<int>("Nivel_Poder")
                        .HasColumnType("int")
                        .HasColumnName("nivel_poder");

                    b.Property<string>("Rol_Equipo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rol_equipo");

                    b.HasKey("Id_Miembro");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("miembro_equipo", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Mision", b =>
                {
                    b.Property<int>("Id_Mision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_mision");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Mision"));

                    b.Property<DateTime>("Fecha_Asignacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_asignacion");

                    b.Property<DateTime?>("Fecha_Fin_Estimada")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin_estimada");

                    b.Property<DateTime?>("Fecha_Fin_Real")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_fin_real");

                    b.Property<DateTime?>("Fecha_Inicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("Id_Comandante")
                        .HasColumnType("int")
                        .HasColumnName("id_comandante");

                    b.Property<int>("Id_Equipo")
                        .HasColumnType("int")
                        .HasColumnName("id_equipo");

                    b.Property<int>("Id_Estado_Mision")
                        .HasColumnType("int")
                        .HasColumnName("id_estado_mision");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<string>("Nombre_Mision")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_mision");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Porcentaje_Avance")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("porcentaje_avance");

                    b.Property<byte>("Prioridad")
                        .HasColumnType("tinyint unsigned")
                        .HasColumnName("prioridad");

                    b.Property<decimal>("Recompensa_Ofrecida")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("recompensa_ofrecida");

                    b.Property<string>("Tipo_Mision")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_mision");

                    b.HasKey("Id_Mision");

                    b.HasIndex("Id_Planeta");

                    b.ToTable("mision");
                });

            modelBuilder.Entity("Orbital.API.Models.Planeta", b =>
                {
                    b.Property<int>("Id_Planeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Planeta"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("activo");

                    b.Property<string>("Color1")
                        .HasColumnType("longtext")
                        .HasColumnName("color1");

                    b.Property<string>("Color2")
                        .HasColumnType("longtext")
                        .HasColumnName("color2");

                    b.Property<string>("Color3")
                        .HasColumnType("longtext")
                        .HasColumnName("color3");

                    b.Property<string>("Conquistado_Por")
                        .HasColumnType("longtext")
                        .HasColumnName("conquistado_por");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<DateTime>("Fecha_Descubrimiento")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_descubrimiento");

                    b.Property<int?>("Id_Atmosfera")
                        .HasColumnType("int")
                        .HasColumnName("id_atmosfera");

                    b.Property<int>("Id_Estado")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<int?>("Id_Galaxia")
                        .HasColumnType("int")
                        .HasColumnName("id_galaxia");

                    b.Property<int?>("Id_Propietario")
                        .HasColumnType("int")
                        .HasColumnName("id_propietario");

                    b.Property<int>("Nivel_Tecnologico")
                        .HasColumnType("int")
                        .HasColumnName("id_nivel_tecnologico");

                    b.Property<string>("Nivel_Vida_Planeta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nivel_vida_planeta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<long?>("Poblacion")
                        .HasColumnType("bigint")
                        .HasColumnName("poblacion");

                    b.HasKey("Id_Planeta");

                    b.HasIndex("Id_Atmosfera");

                    b.HasIndex("Id_Estado");

                    b.HasIndex("Id_Galaxia");

                    b.ToTable("planeta", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.PlanetaEstado", b =>
                {
                    b.Property<int>("Id_Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Estado"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre_estado");

                    b.HasKey("Id_Estado");

                    b.ToTable("estado_planeta", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.PlanetaValoracion", b =>
                {
                    b.Property<int>("Id_Valoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_valoracion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Valoracion"));

                    b.Property<int?>("Aprobado_Por")
                        .HasColumnType("int")
                        .HasColumnName("aprobado_por");

                    b.Property<string>("Clase_Planeta")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("clase_planeta");

                    b.Property<string>("Estado_Valoracion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_valoracion");

                    b.Property<DateTime?>("Fecha_Aprobacion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_aprobacion");

                    b.Property<DateTime>("Fecha_Valoracion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_valoracion");

                    b.Property<int>("Id_Analista")
                        .HasColumnType("int")
                        .HasColumnName("id_analista");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<string>("Observaciones")
                        .HasColumnType("longtext")
                        .HasColumnName("observaciones");

                    b.Property<decimal>("Poder_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("poder_score");

                    b.Property<decimal>("Precio_Final")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_final");

                    b.Property<decimal>("Recursos_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("recursos_score");

                    b.Property<decimal>("Riesgo_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("riesgo_score");

                    b.Property<decimal>("Tecnologia_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("tecnologia_score");

                    b.Property<decimal>("Ubicacion_Score")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("ubicacion_score");

                    b.Property<decimal>("Valor_Total")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id_Valoracion");

                    b.HasIndex("Aprobado_Por");

                    b.HasIndex("Id_Analista");

                    b.HasIndex("Id_Planeta");

                    b.ToTable("planeta_valoracion", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Recurso", b =>
                {
                    b.Property<int>("Id_Recurso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Recurso"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.Property<string>("Rareza")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("rareza");

                    b.Property<string>("Tipo_Recurso")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("tipo_recurso");

                    b.Property<string>("Unidad_Medida")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("unidad_medida");

                    b.HasKey("Id_Recurso");

                    b.ToTable("recurso", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.RecursoPlaneta", b =>
                {
                    b.Property<int>("Id_Recurso_Planeta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_recurso_planeta");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Recurso_Planeta"));

                    b.Property<decimal>("Cantidad_Estimada")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("cantidad_estimada");

                    b.Property<bool>("Extraible")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("extraible");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_registro");

                    b.Property<int>("Id_Planeta")
                        .HasColumnType("int")
                        .HasColumnName("id_planeta");

                    b.Property<int>("Id_Recurso")
                        .HasColumnType("int")
                        .HasColumnName("id_recurso");

                    b.Property<decimal>("Valor_Unitario")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_unitario");

                    b.HasKey("Id_Recurso_Planeta");

                    b.HasIndex("Id_Planeta");

                    b.HasIndex("Id_Recurso");

                    b.ToTable("recurso_planeta");
                });

            modelBuilder.Entity("Orbital.API.Models.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Rol"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nombre_Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Rol");

                    b.ToTable("rol", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.TipoAtmosfera", b =>
                {
                    b.Property<int>("Id_Atmosfera")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_atmosfera");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Atmosfera"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nombre");

                    b.HasKey("Id_Atmosfera");

                    b.ToTable("tipo_atmosfera", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Transaccion", b =>
                {
                    b.Property<int>("Id_Transaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_transaccion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Transaccion"));

                    b.Property<string>("Estado_Transaccion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("estado_transaccion");

                    b.Property<DateTime>("Fecha_Transaccion")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fecha_transaccion");

                    b.Property<int>("Id_Comprador")
                        .HasColumnType("int")
                        .HasColumnName("id_comprador");

                    b.Property<int>("Id_Publicacion")
                        .HasColumnType("int")
                        .HasColumnName("id_publicacion");

                    b.Property<int>("Id_Vendedor")
                        .HasColumnType("int")
                        .HasColumnName("id_vendedor");

                    b.Property<string>("Metodo_Pago")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("metodo_pago");

                    b.Property<string>("Notas")
                        .HasColumnType("longtext")
                        .HasColumnName("notas");

                    b.Property<decimal>("Precio_Final")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("precio_final");

                    b.HasKey("Id_Transaccion");

                    b.ToTable("transaccion");
                });

            modelBuilder.Entity("Orbital.API.Models.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id_Usuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Contrasena_Hash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Fecha_Registro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Id_Jerarquia")
                        .HasColumnType("int");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("Ultimo_Acceso")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("Id_Jerarquia");

                    b.HasIndex("Id_Rol");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("Orbital.API.Models.Cliente", b =>
                {
                    b.HasOne("Orbital.API.Models.Galaxia", "GalaxiaOrigen")
                        .WithMany()
                        .HasForeignKey("Id_Galaxia_Origen")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GalaxiaOrigen");
                });

            modelBuilder.Entity("Orbital.API.Models.CoordenadasPlaneta", b =>
                {
                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithOne("Coordenadas")
                        .HasForeignKey("Orbital.API.Models.CoordenadasPlaneta", "Id_Planeta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Planeta");
                });

            modelBuilder.Entity("Orbital.API.Models.HistoricoCicloPlanetario", b =>
                {
                    b.HasOne("Orbital.API.Models.Cliente", "ClienteAnterior")
                        .WithMany()
                        .HasForeignKey("Id_Cliente_Anterior")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbital.API.Models.Cliente", "ClienteNuevo")
                        .WithMany()
                        .HasForeignKey("Id_Cliente_Nuevo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithMany()
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Transaccion", "Transaccion")
                        .WithMany()
                        .HasForeignKey("Id_Transaccion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteAnterior");

                    b.Navigation("ClienteNuevo");

                    b.Navigation("Planeta");

                    b.Navigation("Transaccion");
                });

            modelBuilder.Entity("Orbital.API.Models.MercadoPlaneta", b =>
                {
                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithMany()
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.PlanetaValoracion", "Valoracion")
                        .WithMany()
                        .HasForeignKey("Id_Valoracion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planeta");

                    b.Navigation("Valoracion");
                });

            modelBuilder.Entity("Orbital.API.Models.MiembroEquipo", b =>
                {
                    b.HasOne("Orbital.API.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Orbital.API.Models.Mision", b =>
                {
                    b.HasOne("Orbital.API.Models.Planeta", null)
                        .WithMany("Misiones")
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Orbital.API.Models.Planeta", b =>
                {
                    b.HasOne("Orbital.API.Models.TipoAtmosfera", "AtmosferaNav")
                        .WithMany()
                        .HasForeignKey("Id_Atmosfera")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbital.API.Models.PlanetaEstado", "Estado")
                        .WithMany()
                        .HasForeignKey("Id_Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Galaxia", "GalaxiaNav")
                        .WithMany()
                        .HasForeignKey("Id_Galaxia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AtmosferaNav");

                    b.Navigation("Estado");

                    b.Navigation("GalaxiaNav");
                });

            modelBuilder.Entity("Orbital.API.Models.PlanetaValoracion", b =>
                {
                    b.HasOne("Orbital.API.Models.Usuario", "AprobadoPor")
                        .WithMany()
                        .HasForeignKey("Aprobado_Por")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Orbital.API.Models.Usuario", "Analista")
                        .WithMany()
                        .HasForeignKey("Id_Analista")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithMany()
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Analista");

                    b.Navigation("AprobadoPor");

                    b.Navigation("Planeta");
                });

            modelBuilder.Entity("Orbital.API.Models.RecursoPlaneta", b =>
                {
                    b.HasOne("Orbital.API.Models.Planeta", "Planeta")
                        .WithMany("Recursos")
                        .HasForeignKey("Id_Planeta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Recurso", "Recurso")
                        .WithMany()
                        .HasForeignKey("Id_Recurso")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Planeta");

                    b.Navigation("Recurso");
                });

            modelBuilder.Entity("Orbital.API.Models.Usuario", b =>
                {
                    b.HasOne("Orbital.API.Models.Jerarquia", "Jerarquia")
                        .WithMany()
                        .HasForeignKey("Id_Jerarquia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Orbital.API.Models.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jerarquia");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("Orbital.API.Models.Planeta", b =>
                {
                    b.Navigation("Coordenadas");

                    b.Navigation("Misiones");

                    b.Navigation("Recursos");
                });
#pragma warning restore 612, 618
        }
    }
}
